# Generated by Django 3.1.6 on 2021-05-17 21:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')])),
                ('number', models.IntegerField(choices=[(2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten'), (11, 'Jack'), (12, 'Queen'), (13, 'King'), (14, 'Ace')])),
                ('code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='PocketHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_one', to='pokerApp.card')),
                ('card_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_two', to='pokerApp.card')),
            ],
        ),
    ]
