# Generated by Django 3.1.6 on 2021-05-17 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerApp', '0002_pockethand_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pockethand',
            name='code',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(169), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
