# Generated by Django 3.1.6 on 2021-05-17 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerApp', '0003_pockethand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pockethand',
            name='code',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2652), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pockethand',
            name='ranking',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(169), django.core.validators.MinValueValidator(1)]),
        ),
    ]
